name: Build Docker

on:
  push:
   branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  RUNNING:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Create Image
        run: docker pull anonymous/mltb:latest 
      - name: Run Image
        run: docker run --env CONFIG_FILE_URL=${{ secrets.CONFIG_FILE_URL }} --env TOKEN_PICKLE_URL=${{ secrets.TOKEN_PICKLE_URL }} anonymous/mltb:latest 
