name: leee

on:
  workflow_dispatch:
jobs:
  RUNNING:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Create Image
        run: docker push downloadyh/ibot:lee
        run: docker pull downloadyh/ibot:lee 
      - name: Run Image
        run: docker run --env CONFIG_FILE_URL=${{ secrets.CONFIG_FILE_URL }} --env TOKEN_PICKLE_URL=${{ secrets.TOKEN_PICKLE_URL }} downloadyh/ibot:lee 
